; Listing generated by Microsoft (R) Optimizing Compiler Version 19.21.27702.2 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\yasya\AppData\Local\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.cpp"
